"""otp phone num added

Revision ID: 6bcd9550f18e
Revises: eac3df139f6a
Create Date: 2025-10-30 23:15:28.558759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcd9550f18e'
down_revision = 'eac3df139f6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('phone', sa.String(length=15), nullable=False))
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_column('otp_codes', 'phone')
    # ### end Alembic commands ###