"""auth migration

Revision ID: 90f1fdfa86a2
Revises: e111158899d3
Create Date: 2025-10-30 21:15:43.575381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f1fdfa86a2'
down_revision = 'e111158899d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###