"""initial migration

Revision ID: e111158899d3
Revises: 
Create Date: 2025-10-30 20:15:35.092213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e111158899d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_number', sa.String(), nullable=True),
    sa.Column('is_occupied', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_spots_id'), 'parking_spots', ['id'], unique=False)
    op.create_index(op.f('ix_parking_spots_spot_number'), 'parking_spots', ['spot_number'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('otp_codes',
    sa.Column('otp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_table('parking_zones',
    sa.Column('parking_zone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('door_no', sa.String(length=20), nullable=True),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('address2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'PUBLIC', 'PARKING_LOT', name='zonetypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('parking_zone_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.Enum('BIKE', 'CAR', 'SEDAN', 'SUV', name='vehicletypeenum'), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('registration_no', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('registration_no')
    )
    op.create_table('parking_space_profiles',
    sa.Column('space_profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parking_zone_id', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.Enum('TWO_WHEELER', 'FOUR_WHEELER', name='slottypeenum'), nullable=False),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('width', sa.String(length=50), nullable=True),
    sa.Column('vehicle_category', sa.Enum('MINI', 'MEDIUM', 'XL', 'VAN', 'ANY', name='vehiclecategoryenum'), nullable=False),
    sa.Column('covered', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('price_per_hour', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_24_hour', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('booking_type', sa.Enum('PREPAY', 'PAY_LATER', name='bookingtypeenum'), nullable=False),
    sa.Column('available_24_7', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parking_zone_id'], ['parking_zones.parking_zone_id'], ),
    sa.PrimaryKeyConstraint('space_profile_id')
    )
    op.create_table('parking_space_schedules',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parking_zone_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', name='dayofweekenum'), nullable=False),
    sa.Column('is_available_24_7', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_not_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parking_zone_id'], ['parking_zones.parking_zone_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('space_profile_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'STARTED', 'COMPLETED', 'CANCELLED', name='bookingstatusenum'), nullable=True),
    sa.Column('booking_type', sa.Enum('PREPAY', 'PAY_LATER', name='bookingtypeenum'), nullable=False),
    sa.Column('amount_expected', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('refund_status', sa.Enum('INITIATED', 'COMPLETED', 'NOT_APPLICABLE', name='refundstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_profile_id'], ['parking_space_profiles.space_profile_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'FILE', 'SYSTEM', name='messagetypeenum'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('check_in_out',
    sa.Column('check_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('check_id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'UPI', name='paymentmethodenum'), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'REFUNDED', 'PENDING', name='paymentstatusenum'), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('check_in_out')
    op.drop_table('chat_messages')
    op.drop_table('bookings')
    op.drop_table('parking_space_schedules')
    op.drop_table('parking_space_profiles')
    op.drop_table('vehicles')
    op.drop_table('parking_zones')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parking_spots_spot_number'), table_name='parking_spots')
    op.drop_index(op.f('ix_parking_spots_id'), table_name='parking_spots')
    op.drop_table('parking_spots')
    # ### end Alembic commands ###