"""otp table change

Revision ID: eac3df139f6a
Revises: 90f1fdfa86a2
Create Date: 2025-10-30 23:00:32.333629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eac3df139f6a'
down_revision = '90f1fdfa86a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('otp_codes_user_id_fkey', 'otp_codes', type_='foreignkey')
    op.drop_column('otp_codes', 'verified_at')
    op.drop_column('otp_codes', 'user_id')
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'phone_verified')
    op.add_column('otp_codes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('otp_codes', sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('otp_codes_user_id_fkey', 'otp_codes', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###