
name: Deploy Serverless Application

on:
  push:
    branches:
      - main
      - pre-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check system versions
        run: |
          lsb_release -a
          node -v || echo "Node.js not installed"
          npm -v || echo "npm not installed"
          nvm -v || echo "nvm not installed"
          python --version || echo "Python not installed"

      - name: Remove existing Node.js and npm
        run: |
          sudo apt-get remove --purge -y nodejs npm
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          sudo rm -rf /usr/local/bin/node
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/include/node

      - name: Install pyenv and Python 3.10
        run: |
          curl https://pyenv.run | bash
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          pyenv install 3.10
          pyenv global 3.10
          python --version

      - name: Install NVM and Node.js
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ ! -d "$HOME/.nvm" ]; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          fi
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 20
          nvm use 20
          npm install -g npm@10.8.2
          # npm install -g @angular/cli@latest
          npm install -g serverless@3.40.0
          echo "Node, Angular, and Serverless installed"
          node -v
          npm -v
          nvm --version
          # ng version || echo "ng not installed"
          npm install --legacy-peer-deps

          case "${GITHUB_REF##*/}" in
            main)
              echo "Deploying to production"
              sls deploy --stage prod --offline false
              ;;
            pre-prod)
              echo "Deploying to pre-production"
              sls deploy --stage preprod --offline false --verbose
              ;;
            
            *)
              echo "Branch not recognized. No deployment done."
              exit 1
              ;;
          esac

      - name: Debug PATH and npm location
        run: |
          echo "PATH: $PATH"
          which npm || echo "npm not found"
          ls -l $(which npm) || echo "npm binary not found"
